export const API_ENDPOINTS = {
  auth: {
    login: '/auth/login',
    register: '/auth/register',
    me: '/auth/me',
    refreshToken: '/auth/refresh',
    logout: '/auth/logout',
  },
  events: {
    list: '/events',
    detail: (id: string) => `/events/${id}`,
    active: '/events/active',
    create: '/events',
    update: (id: string) => `/events/${id}`,
    exhibitors: (id: string) => `/events/${id}/exhibitors`,
    itinerary: (id: string) => `/events/${id}/itinerary`,
    bookmarkItinerary: (itemId: string) => `/itinerary/${itemId}/bookmark`,
  },
  leads: {
    list: '/leads',
    detail: (id: string) => `/leads/${id}`,
    create: '/leads',
    update: (id: string) => `/leads/${id}`,
    delete: (id: string) => `/leads/${id}`,
    notes: (id: string) => `/leads/${id}/notes`,
    activities: (id: string) => `/leads/${id}/activities`,
    attachments: (id: string) => `/leads/${id}/attachments`,
    followUps: (id?: string) => (id ? `/leads/${id}/follow-ups` : '/follow-ups'),
    batchSync: '/leads/sync',
    export: (eventId: string) => `/leads/export?eventId=${eventId}`,
  },
  analytics: {
    metrics: '/analytics/metrics',
    summary: (eventId: string) => `/analytics/events/${eventId}/summary`,
    velocity: (eventId: string) => `/analytics/events/${eventId}/velocity`,
    staff: (eventId: string) => `/analytics/events/${eventId}/staff`,
  },
  team: {
    list: '/team',
    detail: (id: string) => `/team/${id}`,
    invite: '/team/invite',
    updateRole: (id: string) => `/team/${id}/role`,
    updateStatus: (id: string) => `/team/${id}/status`,
  },
  profile: {
    get: '/profile',
    update: '/profile',
    company: (id: string) => `/companies/${id}`,
  },
} as const;
